CREATE TABLE IF NOT EXISTS statistic_hits (
    id BIGSERIAL PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(64) NOT NULL,
    hit_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);