server:
  port: 0

grpc:
  client:
    analyzer:
      address: discovery:///analyzer
      negotiation-type: plaintext
    collector:
      address: discovery:///collector
      negotiation-type: plaintext

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/eventdb
    username: ewmdb
    password: ${EWM_DB_PASSWORD:ewmdb}

logging:
  level:
    ru.practicum: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info